### ISSUE TITLE
Networking - not working - resolving

### ISSUE THREAD

**Issue by Sharky84** [samip5/archlinux-docker#1]
Hallo,

i really appreciate your work. I used it to have the latest calibre-version on my raspberry pi. But with your latest image I can't get it to work anymore. It seems that I can't use pacman. I always get errors like this:
error: failed retrieving file 'core.db' from mirror.archlinuxarm.org : Resolving timed out after 1226238595984 milliseconds
error: failed to update core (download library error)

Can you please help me?

Thank you in advance

Sharky

**Comment by samip5** [comment]
It seems that the most likely culprit is the fact that the mirror is very slow to respond, or that something broke in DNS.
I will need to check that. Please tell me which exact architecture?

P.S I'm very sorry for the late reply as I hadn't gotten any indication from GH about the issue.

**Comment by samip5** [comment]
If this is still the case, please open a new issue.
